# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  format-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: denolib/setup-deno@master
        with:
          # Why don't use latest version? Refer https://github.com/denosaurs/deno_brotli/issues/2
          deno-version: v1.1.2 
      - name: Format Check
        run: sh ./tools/format.sh --check

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: denolib/setup-deno@master
        with:
         deno-version: v1.1.2 
      - name: Bundle levo-runtime
        run: deno run --unstable --allow-run --allow-write tools/bundle-levo-runtime.ts
      - name: Verify levo-runtime-raw.ts is up-to-date
        run: sh ./tools/verify-levo-runtime-raw.sh

  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: denolib/setup-deno@master
        with:
         deno-version: v1.1.2 
      - name: Unit Test
        run: deno test --allow-all --unstable ./test/unit/

  server-test-development-mode:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: denolib/setup-deno@master
        with:
         deno-version: v1.1.2 
      - name: Server Test
        run: deno test --allow-all --unstable ./test/server/development-mode.test.ts

  server-test-production-mode:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: denolib/setup-deno@master
        with:
         deno-version: v1.1.2 
      - name: Server Test
        run: deno test --allow-all --unstable ./test/server/production-mode.test.ts

  template-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: denolib/setup-deno@master
        with:
         deno-version: v1.1.2 
      - name: Template Test
        run: deno test --allow-all --unstable ./test/server/project-template.test.ts 

  cli-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: denolib/setup-deno@master
        with:
         deno-version: v1.1.2 
      - name: CLI Test
        run: deno test --allow-all --unstable ./test/cli/main.test.ts

  levo-runtime-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: denolib/setup-deno@master
        with:
         deno-version: v1.1.2 
      - uses: actions/setup-node@v1
        with: 
          node-version: 10.x
      - name: Install npm packages
        run: npm install
        working-directory: ./test-levo-runtime
      - name: Run test
        run: npm test
        working-directory: ./test-levo-runtime