# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  format-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: denolib/setup-deno@master
        with:
          # Why don't use latest version? Refer https://github.com/denosaurs/deno_brotli/issues/2
          deno-version: v1.0.2 

      - name: Format Check
        run: |
          deno fmt --check demo
          deno fmt --check mod
          deno fmt --check src
          deno fmt --check test
          deno fmt --check templates

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: denolib/setup-deno@master
        with:
         deno-version: v1.0.2 

      - name: Bundle levo-runtime.ts
        run: deno bundle --config tsconfig.json src/levo-runtime.ts > /dev/null

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: denolib/setup-deno@master
        with:
         deno-version: v1.0.2 

      - name: Unit Test
        run: deno test --allow-all --unstable test/unit

      - name: Server Test
        run: deno test --allow-all --unstable test/server/main.test.ts

      - name: Template Test
        run: deno test --allow-all --unstable test/server/project-template.test.ts 

      - name: CLI Test
        run: deno test --allow-all --unstable test/cli/main.test.ts






