# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: denolib/setup-deno@master
        with:
          deno-version: v1.0.2
      - name: Log Deno Version
        run: deno --version

      - name: Format Check
        run: |
          deno fmt --check demo
          deno fmt --check mod
          deno fmt --check src
          deno fmt --check test

      - name: Bundle levo-runtime.ts
        run: deno bundle --config tsconfig.json src/levo-runtime.ts > /dev/null

      - name: Sample test
        run: deno test --unstable sample.test.ts
      
      - name: Unit Test
        run: deno test --allow-all --unstable test/unit

      - name: Server Test
        run: deno test --allow-all --unstable test/server



