# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  format-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: denolib/setup-deno@master
        with:
          # Why don't use latest version? Refer https://github.com/denosaurs/deno_brotli/issues/2
          deno-version: v1.1.1 
      - name: Format Check
        run: |
          deno fmt --check demo
          deno fmt --check mod
          deno fmt --check src
          deno fmt --check test
          deno fmt --check templates
          deno fmt --check cli
          deno fmt --check tools

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: denolib/setup-deno@master
        with:
         deno-version: v1.1.1 
      - name: Verify levo-runtime-raw.ts is updated
        run: |
          deno run --unstable --allow-run --allow-write tools/bundle-levo-runtime.ts
          git status | grep "levo-runtime-raw.ts" \
          && echo "levo-runtime-raw.ts is not up to date" 1>&2 \
          && exit 1

  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: denolib/setup-deno@master
        with:
         deno-version: v1.1.1 
      - name: Unit Test
        run: deno test --allow-all --unstable ./test/unit/

  server-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: denolib/setup-deno@master
        with:
         deno-version: v1.1.1 
      - name: Server Test
        run: deno test --allow-all --unstable ./test/server/main.test.ts

  template-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: denolib/setup-deno@master
        with:
         deno-version: v1.1.1 
      - name: Template Test
        run: deno test --allow-all --unstable ./test/server/project-template.test.ts 

  cli-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: denolib/setup-deno@master
        with:
         deno-version: v1.1.1 
      - name: CLI Test
        run: deno test --allow-all --unstable ./test/cli/main.test.ts